In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('air_quality.csv',low_memory=False)

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5882208 entries, 0 to 5882207
Data columns (total 25 columns):
 #   Column     Dtype
---  ------     -----
 0   date       object
 1   sitename   object
 2   county     object
 3   aqi        float64
 4   pollutant  object
 5   status     object
 6   so2        object
 7   co         object
 8   o3         object
 9   o3_8hr     object
 10  pm10       object
 11  pm2.5      object
 12  no2        object
 13  nox        object
 14  no         object
 15  windspeed  object
 16  winddirec  object
 17  unit       float64
 18  co_8hr     object
 19  pm2.5_avg  object
 20  pm10_avg   object
 21  so2_avg    object
 22  longitude  float64
 23  latitude   float64
 24  siteid     float64
dtypes: float64(5), object(20)
memory usage: 1.1+ GB

In [11]:
data = data.drop(columns=['unit'])

In [16]:
data["so2_avg"] = data["so2_avg"].replace('-', 0.0)

In [20]:
# Calculate the mean of the non-NaN values in the 'so2_avg' column
mean_so2_avg = data['so2_avg'].astype(float).mean()

# Replace NaN values with the calculated mean
data['so2_avg'] = data['so2_avg'].replace(np.nan, mean_so2_avg)

In [21]:
data["so2_avg"].value_counts()

so2_avg
1.0       1683375
2.0       1473087
0.0        918889
3.0        745835
1.6475     629162
4.0        243954
5.0         78582
6.0         29351
1           28716
0           18381
7.0         11899
2            7677
8.0          5180
9.0          2450
3            1500
10.0         1371
11.0          668
12.0          475
13.0          332
4             254
14.0          183
5             169
15.0          127
16.0          101
17.0           84
18.0           80
8              45
6              36
19.0           35
20.0           31
21.0           27
0.0            23
7              21
11             13
-1.0           12
28.0           11
22.0            8
26.0            7
27.0            6
25.0            5
54.0            5
23.0            4
10              4
9               4
50.0            4
31.0            3
29.0            3
32.0            2
49.0            2
47.0            2
36.0            2
24.0            2
51.0            2
41.0            1
48.0            1
55.0            1
44.0            1
30.0            1
60.0            1
37.0            1
Name: count, dtype: int64

In [22]:
data["status"].value_counts()

status
Good                              3185191
Moderate                          2159158
Unhealthy for Sensitive Groups     343909
Unhealthy                           51008
Very Unhealthy                        173
Hazardous                              51
Name: count, dtype: int64

In [ ]:
status_dict = {'Good': 0, 'Moderate': 1, 'Unhealthy for Sensitive Groups': 2, 'Unhealthy': 3, 'Very Unhealthy': 4, 'Hazardous': 5}

In [25]:
data['aqi'].isna().value_counts()

aqi
False    5839188
True       43020
Name: count, dtype: int64

In [10]:
data

,date,sitename,county,aqi,pollutant,status,so2,co,o3,o3_8hr,...,windspeed,winddirec,unit,co_8hr,pm2.5_avg,pm10_avg,so2_avg,longitude,latitude,siteid
0,2024-08-31 23:00,Hukou,Hsinchu County,62.0,PM2.5,Moderate,0.9,0.17,35.0,40.2,...,2.3,225,NaN,0.2,20.1,26.0,1.0,121.038869,24.900097,22.0
1,2024-08-31 23:00,Zhongming,Taichung City,50.0,NaN,Good,1.6,0.32,27.9,35.1,...,1.1,184,NaN,0.2,15.3,23.0,1.0,120.641092,24.151958,31.0
2,2024-08-31 23:00,Zhudong,Hsinchu County,45.0,NaN,Good,0.4,0.17,25.1,40.6,...,0.4,210,NaN,0.2,13.8,24.0,0.0,121.088955,24.740914,23.0
3,2024-08-31 23:00,Hsinchu,Hsinchu City,42.0,NaN,Good,0.8,0.2,30.0,35.9,...,1.9,239,NaN,0.2,13.0,26.0,1.0,120.972368,24.805636,24.0
4,2024-08-31 23:00,Toufen,Miaoli County,50.0,NaN,Good,1.0,0.16,33.5,35.9,...,1.8,259,NaN,0.1,15.3,28.0,1.0,120.898693,24.696907,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5882203,2016-11-25 13:00,Daliao,Kaohsiung City,77.0,PM2.5,Moderate,8.0,0.54,36,12.0,...,2.9,202.0,NaN,0.63,26.0,74.0,NaN,NaN,NaN,NaN
5882204,2016-11-25 13:00,Linyuan,Kaohsiung City,77.0,PM2.5,Moderate,4.6,0.31,94,41.0,...,2.5,224.0,NaN,0.46,26.0,39.0,NaN,NaN,NaN,NaN
5882205,2016-11-25 13:00,Nanzi,Kaohsiung City,74.0,PM2.5,Moderate,4.2,0.3,90,31.0,...,1.9,242.0,NaN,0.41,25.0,88.0,NaN,NaN,NaN,NaN
5882206,2016-11-25 13:00,Zuoying,Kaohsiung City,99.0,PM2.5,Moderate,6.7,0.62,115,40.0,...,2.8,280.0,NaN,0.63,35.0,65.0,NaN,NaN,NaN,NaN
5882207,2016-11-25 13:00,Qianjin,Kaohsiung City,84.0,PM2.5,Moderate,2.9,0.47,76,34.0,...,3.6,290.0,NaN,0.62,29.0,66.0,NaN,NaN,NaN,NaN

In [5]:
data.describe()

                aqi  unit     longitude      latitude        siteid
count  5.839188e+06   0.0  4.948588e+06  4.948588e+06  4.102739e+06
mean   5.419277e+01   NaN  1.208235e+02  2.404500e+01  5.608608e+01
std    2.985864e+01   NaN  9.644120e-01  1.002014e+00  6.233482e+01
min   -1.000000e+00   NaN  0.000000e+00  0.000000e+00  0.000000e+00
25%    3.200000e+01   NaN  1.203455e+02  2.304820e+01  2.100000e+01
50%    4.600000e+01   NaN  1.206853e+02  2.415196e+01  4.200000e+01
75%    7.000000e+01   NaN  1.214492e+02  2.501297e+01  6.500000e+01
max    5.000000e+02   NaN  1.218157e+02  2.625800e+01  3.140000e+02